/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Fern
 */
public class improvedVersion extends javax.swing.JFrame {

    /**
     * Creates new form improvedVersion
     */
    String Player,C1,C2,C3,C4,C5,C6,C7,C8,C9;
    boolean turn,win;
    public improvedVersion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        designpanel = new javax.swing.JPanel();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        messageBox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Improved Version");
        setMaximumSize(new java.awt.Dimension(315, 390));
        setMinimumSize(new java.awt.Dimension(315, 390));
        setPreferredSize(new java.awt.Dimension(315, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        designpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        designpanel.setMaximumSize(new java.awt.Dimension(300, 300));
        designpanel.setMinimumSize(new java.awt.Dimension(300, 300));
        designpanel.setLayout(null);

        c1.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c1.setText("1");
        c1.setFocusPainted(false);
        c1.setFocusable(false);
        c1.setMaximumSize(new java.awt.Dimension(100, 100));
        c1.setMinimumSize(new java.awt.Dimension(100, 100));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        designpanel.add(c1);
        c1.setBounds(0, 0, 100, 100);

        c2.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c2.setText("2");
        c2.setFocusPainted(false);
        c2.setFocusable(false);
        c2.setMaximumSize(new java.awt.Dimension(100, 100));
        c2.setMinimumSize(new java.awt.Dimension(100, 100));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        designpanel.add(c2);
        c2.setBounds(100, 0, 100, 100);

        c3.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c3.setText("3");
        c3.setFocusPainted(false);
        c3.setFocusable(false);
        c3.setMaximumSize(new java.awt.Dimension(100, 100));
        c3.setMinimumSize(new java.awt.Dimension(100, 100));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        designpanel.add(c3);
        c3.setBounds(200, 0, 100, 100);

        c4.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c4.setText("4");
        c4.setFocusPainted(false);
        c4.setFocusable(false);
        c4.setMaximumSize(new java.awt.Dimension(100, 100));
        c4.setMinimumSize(new java.awt.Dimension(100, 100));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        designpanel.add(c4);
        c4.setBounds(0, 100, 100, 100);

        c5.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c5.setText("5");
        c5.setFocusPainted(false);
        c5.setFocusable(false);
        c5.setMaximumSize(new java.awt.Dimension(100, 100));
        c5.setMinimumSize(new java.awt.Dimension(100, 100));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        designpanel.add(c5);
        c5.setBounds(100, 100, 100, 100);

        c6.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c6.setText("6");
        c6.setFocusPainted(false);
        c6.setFocusable(false);
        c6.setMaximumSize(new java.awt.Dimension(100, 100));
        c6.setMinimumSize(new java.awt.Dimension(100, 100));
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        designpanel.add(c6);
        c6.setBounds(200, 100, 100, 100);

        c7.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c7.setText("7");
        c7.setFocusPainted(false);
        c7.setFocusable(false);
        c7.setMaximumSize(new java.awt.Dimension(100, 100));
        c7.setMinimumSize(new java.awt.Dimension(100, 100));
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        designpanel.add(c7);
        c7.setBounds(0, 200, 100, 100);

        c8.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c8.setText("8");
        c8.setFocusPainted(false);
        c8.setFocusable(false);
        c8.setMaximumSize(new java.awt.Dimension(100, 100));
        c8.setMinimumSize(new java.awt.Dimension(100, 100));
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        designpanel.add(c8);
        c8.setBounds(100, 200, 100, 100);

        c9.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        c9.setText("9");
        c9.setFocusPainted(false);
        c9.setFocusable(false);
        c9.setMaximumSize(new java.awt.Dimension(100, 100));
        c9.setMinimumSize(new java.awt.Dimension(100, 100));
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });
        designpanel.add(c9);
        c9.setBounds(200, 200, 100, 100);

        getContentPane().add(designpanel);
        designpanel.setBounds(5, 5, 300, 300);

        messageBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        messageBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageBox.setText("Player X's Turn");
        messageBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        messageBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageBoxMouseClicked(evt);
            }
        });
        getContentPane().add(messageBox);
        messageBox.setBounds(10, 320, 290, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c1.setText(Player);
        getValues();
        if(checkCells(C1,C2,C3)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C1,C4,C7)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C1,C5,C9)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C1,C2,C3)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C1,C4,C7)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C1,C5,C9)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c2.setText(Player);
        getValues();
        if(checkCells(C2,C1,C3)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C2,C5,C8)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C2,C1,C3)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C2,C5,C8)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c3.setText(Player);
        getValues();
        if(checkCells(C3,C2,C1)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C3,C6,C9)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C3,C5,C7)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C3,C2,C1)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C3,C6,C9)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C3,C5,C7)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c4.setText(Player);
        getValues();
        if(checkCells(C4,C1,C7)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C4,C5,C6)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C4,C1,C7)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C4,C5,C6)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c5.setText(Player);
        getValues();
        if(checkCells(C5,C2,C8)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C5,C4,C6)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C5,C1,C9)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C5,C3,C7)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C5,C2,C8)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C5,C4,C6)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C5,C1,C9)){
                messageBox.setText("Player O wins!");
                won(true);
            }
            else if(checkCells(C5,C3,C7)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c6.setText(Player);
        getValues();
        if(checkCells(C6,C3,C9)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C6,C5,C4)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C6,C3,C9)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C6,C5,C4)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c7.setText(Player);
        getValues();
        if(checkCells(C7,C4,C1)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C7,C5,C3)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C7,C8,C9)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C7,C4,C1)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C7,C5,C3)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C7,C8,C9)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c7ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c8.setText(Player);
        getValues();
        if(checkCells(C8,C7,C9)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C8,C5,C2)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C8,C7,C9)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C8,C5,C2)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c8ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
        currentPlayer();
        c9.setText(Player);
        getValues();
        if(checkCells(C9,C6,C3)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C9,C5,C1)){
            messageBox.setText("Player X wins!");
            won(true);
        }else if(checkCells(C9,C8,C7)){
            messageBox.setText("Player X wins!");
            won(true);
        }else{
            if(checkCells(C9,C6,C3)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C9,C5,C1)){
                messageBox.setText("Player O wins!");
                won(true);
            }else if(checkCells(C9,C8,C7)){
                messageBox.setText("Player O wins!");
                won(true);
            }
        }
    }//GEN-LAST:event_c9ActionPerformed

    private void messageBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageBoxMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_messageBoxMouseClicked

    public void draw(){
        messageBox.setToolTipText("Click to play again");
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        c6.setEnabled(false);
        c7.setEnabled(false);
        c8.setEnabled(false);
        c9.setEnabled(false);
    }
    
    public void reset(){
        turn = false;
        if(win==true){
            messageBox.setText("Player X's Turn");
            messageBox.setToolTipText(null);
            c1.setText("1");
            c2.setText("2");
            c3.setText("3");
            c4.setText("4");
            c5.setText("5");
            c6.setText("6");
            c7.setText("7");
            c8.setText("8");
            c9.setText("9");
            c1.setEnabled(true);
            c2.setEnabled(true);
            c3.setEnabled(true);
            c4.setEnabled(true);
            c5.setEnabled(true);
            c6.setEnabled(true);
            c7.setEnabled(true);
            c8.setEnabled(true);
            c9.setEnabled(true);
        }
    }
    public void won(boolean win){
        if(win==true){
        messageBox.setToolTipText("Click to play again");
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        c6.setEnabled(false);
        c7.setEnabled(false);
        c8.setEnabled(false);
        c9.setEnabled(false);
    }
    }
    public boolean checkCells(String c1,String c2,String c3){
            String arr[] = {c1,c2,c3};
            Set<String> s = new HashSet<>(Arrays.asList(arr));
            return (s.size() == 1);
    }
    public void currentPlayer(){
        if(turn  == true){
            messageBox.setText("Player X's Turn");
            Player = "O";
            turn = false;
        }else{
            messageBox.setText("Player O's Turn");
            Player = "X";
            turn = true;
        }
    }
    public void getValues(){
        C1 = c1.getText();
        C2 = c2.getText();
        C3 = c3.getText();
        C4 = c4.getText();
        C5 = c5.getText();
        C6 = c6.getText();
        C7 = c7.getText();
        C8 = c8.getText();
        C9 = c9.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(improvedVersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(improvedVersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(improvedVersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(improvedVersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new improvedVersion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JPanel designpanel;
    private javax.swing.JLabel messageBox;
    // End of variables declaration//GEN-END:variables
}
